extraEnvs:
  - name: NODE_NAME
    valueFrom:
      fieldRef:
        fieldPath: spec.nodeName

mode: daemonset

# https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/UPGRADING.md
image:
  repository: "otel/opentelemetry-collector-k8s"

config:
  exporters:
    otlp:
      # service name created using the standalone collector i.e. using the deployment
      endpoint: otel-collector-standalone-opentelemetry-collector:4317
      tls:
        insecure: true
    debug:
      verbosity: detailed
  processors:
    resource:
      attributes:
        - key: k8s.node.name
          value: ${NODE_NAME}
          action: upsert
  service:
    telemetry:
      logs:
        level: DEBUG
    pipelines:
      logs:
        exporters:
          - otlp
          - debug
        processors:
          - batch
          - memory_limiter
          - resource
      metrics:
        exporters:
          - otlp
          - debug
        processors:
          - batch
          - memory_limiter
          - resource
      traces:
        exporters:
          - otlp
          - debug
        processors:
          - batch
          - memory_limiter
          - resource
