receivers:
  otlp:
    protocols:
      grpc:

exporters:
  debug:
    verbosity: detailed


processors:
  tail_sampling:
    decision_wait: 5s
    # For example, you may want to continue capturing only 10% of all traces but always
    # capture traces representing operations that took longer than 1 second to complete.
    policies:
      [
        {
          name: probability,
          type: probabilistic,
          probabilistic: { sampling_percentage: 10 },
        },
        # Supplying no upper bound will result in a policy sampling anything greater than threshold_ms
        { name: slow, type: latency, latency: { threshold_ms: 1000 } },
      ]

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling]
      exporters: [debug]
