receivers:
  otlp:
    protocols:
      grpc:
exporters:
  debug:
    verbosity: detailed
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans
  otlp/jaeger: # <2>
    # https://opentelemetry.io/blog/2023/jaeger-exporter-collector-migration/
    endpoint: jaeger:4317
    tls:
      insecure: true
  prometheus:
    endpoint: 0.0.0.0:8889
    resource_to_telemetry_conversion:
      enabled: true
  loki:
    endpoint: http://loki:3100/loki/api/v1/push



processors:
  resource:
    attributes:
      - action: insert
        key: loki.resource.labels
        value: service.name

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug, zipkin, otlp/jaeger, debug]
    metrics:
      receivers: [otlp]
      exporters: [debug, prometheus, debug]
    logs:
      receivers: [otlp]
      processors: [resource]
      exporters: [debug, loki, debug]
